version: "3"
services:
  nodeapp:
    build: 
      context: ./node
      dockerfile: Dockerfile
    container_name: node-dev
    tty: true
    volumes:
      - ./node/app:/app
    ports:
      - "8080:3000"
    links:
      - postgresql
  postgresql:
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
